### PR TITLE
Fixes #6 - fix typo

### LINKED ISSUE #6: Some typos meta issue
(I will add a list here if I found more.)

* [x] We have three different **setps** to setup the project. You do not need to finish all 3 steps
* [x] Let´s (using ACUTE ACCENT instead of ' or ’)

### PR DESCRIPTION
**Pull request by zoepage**
r? @karlcow 

(Semicolon typo is not a typo as we need this, otherwise the multi line string would break)

### CODE REVIEW

**Comment by zoepage** [comment]
@karlcow not sure, why I wrote `semicolon`... I meant ` .

**Comment by karlcow** [comment]
> @karlcow not sure, why I wrote semicolon... I meant ` .

But I'm not talking about the back tick either ;)

**Comment by zoepage** [comment]
@karlcow I guess, I really need some sleep :D 
Fixed.

**Comment by karlcow** [comment]
💯 super.

**Pull request merged**
